### ISSUE TITLE
设置页面完成

### ISSUE THREAD

**Issue by VecHK** [VecHK/poker#3]
实现发牌页面的管理

1.0 包括：

- [x]  **添加/删除 新的搜索页（新的牌）**
- [x]  **修改发牌的顺序**
用户能够在设置中，使用拖拽的方式修改页面（卡牌）的弹出排序
- [x]  **字符串搜索（Poker + xxx）的开关**
- [x]  **如果便捷加入网站的地址栏按钮也做了的话，在设置里也做个开关**

**Comment by nt-cubic** [comment]
![Z6JEV1Z225$RTRJUE$_6Q(N](https://user-images.githubusercontent.com/88926027/167251603-2e8c5af1-e039-4b7f-a5b3-c5c3ed6f1d14.png)
设置页面的最新UI

考虑到本插件目前只支持电脑端，因此重新布局了电脑端UI
左边一栏的关于和使用方式，未来可以通过实现notion的折叠功能进行处理。
左边一栏用于放置开关、跳转、按钮等杂项。
右边全面使用发牌手设置布局。
