### ISSUE TITLE
设置页面优化

### ISSUE THREAD

**Issue by VecHK** [VecHK/poker#36]
### 需要优化编辑站点的交互（加动画）
 - 在一行中添加一个新的站点
 - 新增一行改成拖拽式

### 清空掉所有的站点的时候，需要能提醒用户（控制窗里也加上这种提示）

**Comment by nt-cubic** [comment]
![6962E91C8AF32630EC2B0ABA3C3311E9](https://user-images.githubusercontent.com/88926027/168213299-83b5d284-ec55-4f8b-8440-9d0ab169fb7e.jpg)
每一层，要是可以加牌，就放一个＋的框到这一层的末尾。
而令起一层的交互，便是永远会在最上面多出一层，这一层第一个就是这个＋，便于用户加层。

下面这个就不要了
