### ISSUE TITLE
消除掉页面的『关闭』与『最小化』按钮

### ISSUE THREAD

**Issue by VecHK** [VecHK/poker#6]
要是每个页面都有『最小化』『最大化』『关闭』的按钮，容易混淆是非，**用户不知道按哪里才能全部关闭。**

我记忆中 Chrome 那些谷歌关联登录时，那些页面是没有这三个按钮的。不知道官方手册有没有提供这个方法进行展开？

**Comment by nt-cubic** [comment]
**更新：『最大化』需要进行保留**
用户点击最大化时，能够通过在浏览器已有窗口中新开标签页的方式进行页面展开。

**Comment by nt-cubic** [comment]
**更新**
点击最大化后，原先的页面不会删除。是直接新增一个标签到浏览器窗口里
